title: Developer Holywater Jeong
description: 개발자 정성수의 기술(?) 블로그

url: https://holywater-jeong.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Categories
    url: /category

social:
   github: holywater-jeong
   twitter:
   facebook: holywaterjeong
   email: holywaterj0410@gmail.com

google_analytics: "UA-89636374-2"
